import { CharacterColorData } from '../../types';

export const character_card_colors: CharacterColorData[] = [
  { id: 1, name: 'Luke Skywalker', primaryColor: '#0000FF' },
  { id: 2, name: 'C-3PO', primaryColor: '#FFFF00' },
  { id: 3, name: 'R2-D2', primaryColor: '#ADD8E6' },
  { id: 4, name: 'Darth Vader', primaryColor: '#8B0000' },
  { id: 5, name: 'Leia Organa', primaryColor: '#800080' },
  { id: 6, name: 'Owen Lars', primaryColor: '#008000' },
  { id: 7, name: 'Beru Whitesun lars', primaryColor: '#008080' },
  { id: 8, name: 'R5-D4', primaryColor: '#FF0000' },
  { id: 9, name: 'Biggs Darklighter', primaryColor: '#FFA500' },
  { id: 10, name: 'Obi-Wan Kenobi', primaryColor: '#ADD8E6' },
  { id: 11, name: 'Anakin Skywalker', primaryColor: '#00008B' },
  { id: 13, name: 'Chewbacca', primaryColor: '#006400' },
  { id: 14, name: 'Han Solo', primaryColor: '#8B4513' },
  { id: 15, name: 'Greedo', primaryColor: '#006400' },
  { id: 16, name: 'Jabba Desilijic Tiure', primaryColor: '#A52A2A' },
  { id: 18, name: 'Wedge Antilles', primaryColor: '#FFA500' },
  { id: 20, name: 'Yoda', primaryColor: '#90EE90' },
  { id: 21, name: 'Palpatine', primaryColor: '#800080' },
  { id: 22, name: 'Boba Fett', primaryColor: '#A9A9A9' },
  { id: 24, name: 'Bossk', primaryColor: '#006400' },
  { id: 25, name: 'Lando Calrissian', primaryColor: '#00008B' },
  { id: 26, name: 'Lobot', primaryColor: '#D3D3D3' },
  { id: 27, name: 'Ackbar', primaryColor: '#00008B' },
  { id: 28, name: 'Mon Mothma', primaryColor: '#D8BFD8' },
  { id: 29, name: 'Arvel Crynyd', primaryColor: '#FFA500' },
  { id: 30, name: 'Wicket Systri Warrick', primaryColor: '#8B4513' },
  { id: 31, name: 'Nien Nunb', primaryColor: '#D3D3D3' },
  { id: 32, name: 'Qui-Gon Jinn', primaryColor: '#F5DEB3' },
  { id: 33, name: 'Nute Gunray', primaryColor: '#006400' },
  { id: 35, name: 'Padmé Amidala', primaryColor: '#D8BFD8' },
  { id: 36, name: 'Jar Jar Binks', primaryColor: '#FF8C00' },
  { id: 37, name: 'Darth Maul', primaryColor: '#8B0000' },
  { id: 38, name: 'Shmi Skywalker', primaryColor: '#F5DEB3' },
  { id: 39, name: 'Captain Panaka', primaryColor: '#00008B' },
  { id: 40, name: 'Watto', primaryColor: '#00008B' },
  { id: 41, name: 'Sebulba', primaryColor: '#A9A9A9' },
  { id: 42, name: 'Eirtaé', primaryColor: '#ADD8E6' },
  { id: 43, name: 'Tarpals', primaryColor: '#A9A9A9' },
  { id: 44, name: 'Ben Quadinaros', primaryColor: '#006400' },
  { id: 51, name: 'Mace Windu', primaryColor: '#800080' },
  { id: 52, name: 'Ki-Adi-Mundi', primaryColor: '#FFFFE0' },
  { id: 53, name: 'Kit Fisto', primaryColor: '#006400' },
  { id: 54, name: 'Eeth Koth', primaryColor: '#8B4513' },
  { id: 55, name: 'Adi Gallia', primaryColor: '#00008B' },
  { id: 56, name: 'Saesee Tiin', primaryColor: '#FF8C00' },
  { id: 57, name: 'Yarael Poof', primaryColor: '#D3D3D3' },
  { id: 58, name: 'Plo Koon', primaryColor: '#FF8C00' },
  { id: 59, name: 'Mas Amedda', primaryColor: '#00008B' },
  { id: 60, name: 'Gregar Typho', primaryColor: '#A9A9A9' },
  { id: 61, name: 'Cordé', primaryColor: '#FFB6C1' },
  { id: 62, name: 'Cliegg Lars', primaryColor: '#F5DEB3' },
  { id: 63, name: 'Poggle the Lesser', primaryColor: '#006400' },
  { id: 64, name: 'Luminara Unduli', primaryColor: '#FFD700' },
  { id: 65, name: 'Barriss Offee', primaryColor: '#00008B' },
  { id: 66, name: 'Dormé', primaryColor: '#ADD8E6' },
  { id: 67, name: 'Dooku', primaryColor: '#A9A9A9' },
  { id: 68, name: 'Bail Prestor Organa', primaryColor: '#00008B' },
  { id: 69, name: 'Jango Fett', primaryColor: '#A9A9A9' },
  { id: 70, name: 'Zam Wesell', primaryColor: '#800080' },
  { id: 71, name: 'Dex', primaryColor: '#A9A9A9' },
  { id: 72, name: 'Lama Su', primaryColor: '#D3D3D3' },
  { id: 73, name: 'Taun We', primaryColor: '#D3D3D3' },
  { id: 74, name: 'Jocasta Nu', primaryColor: '#ADD8E6' },
  { id: 75, name: 'R4-P17', primaryColor: '#8B0000' },
  { id: 76, name: 'Wat Tambor', primaryColor: '#006400' },
  { id: 77, name: 'San Hill', primaryColor: '#D3D3D3' },
  { id: 78, name: 'Shaak Ti', primaryColor: '#8B0000' },
  { id: 79, name: 'Grievous', primaryColor: '#D2B48C' },
  { id: 80, name: 'Tarfful', primaryColor: '#8B4513' },
  { id: 81, name: 'Raymus Antilles', primaryColor: '#00008B' },
  { id: 82, name: 'Sly Moore', primaryColor: '#D3D3D3' },
  { id: 83, name: 'Tion Medon', primaryColor: '#A9A9A9' },
  { id: 84, name: 'Finn', primaryColor: '#8B4513' },
  { id: 85, name: 'Rey', primaryColor: '#F5DEB' },
];
